# Generated by Django 4.2 on 2023-04-23 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mattress',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
