# Generated by Django 4.2 on 2023-04-23 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_mattress_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mattress',
            name='mclass',
            field=models.CharField(choices=[('Premium', 'Premium'), ('Standard', 'Standard'), ('Bestseller', 'Bestseller'), ('Lux', 'Lux')], default='Standard', max_length=255),
        ),
    ]
